export interface LectureDescription {
  aliases: string[];
  text: string;
}

const STRUCTURE_DESCRIPTIONS: LectureDescription[] = [
  {aliases:['clavicle'],text:'Location: anterior shoulder girdle between sternum and scapula. Articulations: sternal end with the manubrium at the sternoclavicular joint; acromial end with the acromion at the acromioclavicular joint. Attachments: conoid ligament to the conoid tubercle, trapezoid ligament to the trapezoid line, and costoclavicular ligament near the medial inferior surface.'},
  {aliases:['scapula'],text:'Location: posterolateral thoracic wall, approximately ribs 2–7. Attachments: supraspinatus arises from the supraspinous fossa; infraspinatus from the infraspinous fossa; subscapularis from the subscapular fossa. The medial border receives serratus anterior, rhomboids and levator scapulae; the lateral border gives attachment to teres minor and teres major. The glenoid cavity articulates with the humeral head.'},
  {aliases:['humerus'],text:'Location: bone of the arm from shoulder to elbow. Articulations: humeral head with the glenoid; capitulum with radius; trochlea with ulna. Attachments: supraspinatus, infraspinatus and teres minor insert on the greater tubercle; subscapularis inserts on the lesser tubercle. Pectoralis major inserts on the lateral lip, teres major on the medial lip, and latissimus dorsi on the floor of the intertubercular sulcus. The radial nerve runs in the radial groove; the axillary nerve passes around the surgical neck.'},
  {aliases:['radius'],text:'Location: lateral forearm bone on the thumb side. Proximally the head articulates with the capitulum and radial notch of the ulna; distally it articulates with the scaphoid and lunate. Biceps brachii inserts on the radial tuberosity. The interosseous membrane attaches along the interosseous border and links the radius to the ulna.'},
  {aliases:['ulna'],text:'Location: medial forearm bone on the little-finger side. The trochlear notch articulates with the humeral trochlea and the radial notch with the radial head. Triceps inserts on the olecranon; brachialis inserts on the ulnar tuberosity and coronoid process. The interosseous membrane attaches along the interosseous border.'},
  {aliases:['glenoid labrum'],text:'Location: fibrocartilaginous rim around the glenoid cavity. Attachment: fixed to the glenoid margin and continuous superiorly with the tendon of the long head of biceps. Function: deepens the socket and increases glenohumeral stability.'},
  {aliases:['sternoclavicular joint'],text:'Location: between the medial clavicle and manubrium, with contribution from the first costal cartilage. It is the only bony articulation linking the upper limb girdle to the axial skeleton. The joint disc and surrounding sternoclavicular and costoclavicular ligaments reinforce it.'},
  {aliases:['acromioclavicular joint'],text:'Location: between the acromial end of the clavicle and acromion of the scapula. The acromioclavicular ligament reinforces the capsule; the coracoclavicular ligament provides major vertical stability through its conoid and trapezoid parts.'},
  {aliases:['glenohumeral joint','shoulder joint'],text:'Location: articulation between the humeral head and glenoid cavity. Stability is supported by the glenoid labrum, capsule, rotator-cuff tendons, coracohumeral ligament and glenohumeral ligaments. Blood supply includes circumflex humeral and suprascapular branches.'},
  {aliases:['coracoclavicular ligament'],text:'Attachment: from the coracoid process to the inferior clavicle. It has two parts: the conoid ligament attaches to the conoid tubercle, and the trapezoid ligament to the trapezoid line. It is a major stabilizer of the acromioclavicular region.'},
  {aliases:['coracoacromial ligament'],text:'Attachment: spans from the coracoid process to the acromion, forming the coracoacromial arch above the humeral head. It helps limit superior displacement of the humeral head.'},
  {aliases:['transverse humeral ligament'],text:'Attachment: bridges the greater and lesser tubercles across the intertubercular groove. It helps retain the tendon of the long head of biceps within the groove.'},

  {aliases:['subclavius'],text:'Origin: junction of the first rib and its costal cartilage. Insertion: inferior surface of the middle third of the clavicle. Innervation: nerve to subclavius, mainly C5–C6. Action: anchors and depresses the clavicle. Location: deep to the clavicle in the superior anterior chest.'},
  {aliases:['pectoralis minor'],text:'Origin: anterior surfaces of ribs 3–5 near their costal cartilages. Insertion: medial border and superior surface of the coracoid process. Innervation: medial pectoral nerve, with contribution from lateral pectoral nerve. Action: draws the scapula anteriorly and inferiorly and can assist forced inspiration.'},
  {aliases:['serratus anterior'],text:'Origin: external surfaces of the upper eight or nine ribs. Insertion: anterior surface of the medial border of the scapula, including the inferior angle. Innervation: long thoracic nerve, C5–C7. Action: protracts the scapula, holds it against the thoracic wall and assists upward rotation.'},
  {aliases:['trapezius'],text:'Origin: external occipital region, nuchal ligament and spinous processes C7–T12. Insertion: posterior lateral clavicle, acromion and spine of scapula. Innervation: spinal accessory nerve (CN XI) with cervical sensory/proprioceptive fibers. Blood supply: superficial branch of transverse cervical artery. Action: elevates, retracts, depresses and upwardly rotates the scapula.'},
  {aliases:['levator scapulae'],text:'Origin: posterior tubercles of transverse processes C1–C4. Insertion: medial border of scapula above the root of the spine and near the superior angle. Innervation: dorsal scapular nerve with cervical branches. Action: elevates and downwardly rotates the scapula.'},
  {aliases:['rhomboid minor'],text:'Origin: nuchal ligament and spinous processes C7–T1. Insertion: medial end of the scapular spine. Innervation: dorsal scapular nerve. Action: retracts and downwardly rotates the scapula and fixes it to the thoracic wall.'},
  {aliases:['rhomboid major'],text:'Origin: spinous processes T2–T5. Insertion: medial border of scapula from the level of the spine toward the inferior angle. Innervation: dorsal scapular nerve. Action: retracts and downwardly rotates the scapula.'},
  {aliases:['supraspinatus'],text:'Origin: supraspinous fossa of scapula. Insertion: superior facet of the greater tubercle of humerus. Innervation: suprascapular nerve, C5–C6. Blood supply: suprascapular artery. Action: initiates shoulder abduction and contributes to rotator-cuff stabilization.'},
  {aliases:['infraspinatus'],text:'Origin: infraspinous fossa of scapula. Insertion: middle facet of the greater tubercle of humerus. Innervation: suprascapular nerve, C5–C6. Blood supply: suprascapular and circumflex scapular arteries. Action: lateral rotation and stabilization of the humeral head.'},
  {aliases:['teres minor'],text:'Origin: middle part of the lateral border of scapula. Insertion: inferior facet of the greater tubercle of humerus. Innervation: axillary nerve. Blood supply: circumflex scapular/posterior circumflex humeral branches. Action: lateral rotation and weak adduction; stabilizes the glenohumeral joint.'},
  {aliases:['subscapularis'],text:'Origin: subscapular fossa. Insertion: lesser tubercle of humerus. Innervation: upper and lower subscapular nerves. Action: medial rotation and adduction of the arm and stabilization of the humeral head.'},
  {aliases:['teres major'],text:'Origin: posterior surface of the inferior angle and adjacent lateral border of scapula. Insertion: medial lip of the intertubercular sulcus of humerus. Innervation: lower subscapular nerve. Action: adducts, medially rotates and extends the arm.'},
  {aliases:['deltoid'],text:'Origin: lateral third of clavicle, acromion and spine of scapula. Insertion: deltoid tuberosity of humerus. Innervation: axillary nerve, C5–C6. Blood supply: posterior circumflex humeral and deltoid branch of thoracoacromial artery. Action: major abductor of the arm after initiation by supraspinatus; anterior and posterior fibers also flex/medially rotate and extend/laterally rotate respectively.'},
  {aliases:['pectoralis major'],text:'Origin: medial clavicle, sternum and upper costal cartilages, with abdominal/aponeurotic contribution inferiorly. Insertion: lateral lip of the intertubercular sulcus of humerus. Innervation: lateral and medial pectoral nerves. Action: adducts and medially rotates the humerus; clavicular fibers flex the arm.'},
  {aliases:['latissimus dorsi'],text:'Origin: lower thoracic and lumbar spinous processes through thoracolumbar fascia, iliac crest, sacrum and lower ribs. Insertion: floor of the intertubercular sulcus of humerus. Innervation: thoracodorsal nerve. Blood supply: thoracodorsal artery. Action: extends, adducts and medially rotates the arm.'},
  {aliases:['biceps brachii'],text:'Origin: long head from the supraglenoid tubercle and glenoid labral region; short head from the coracoid process. Insertion: radial tuberosity and forearm fascia through the bicipital aponeurosis. Innervation: musculocutaneous nerve, C5–C6. Action: powerful forearm supination and elbow flexion; assists shoulder flexion.'},
  {aliases:['triceps brachii'],text:'Origin: long head from infraglenoid tubercle; lateral and medial heads from posterior humerus on opposite sides of the radial groove. Insertion: olecranon of ulna. Innervation: radial nerve. Action: principal elbow extensor; long head also assists shoulder extension and adduction.'},
  {aliases:['coracobrachialis'],text:'Origin: coracoid process with the short head of biceps. Insertion: middle third of medial humeral shaft. Innervation: musculocutaneous nerve, which typically pierces the muscle. Action: flexes and adducts the arm.'},
  {aliases:['brachialis'],text:'Origin: distal half of anterior humerus. Insertion: ulnar tuberosity and coronoid process. Innervation: mainly musculocutaneous nerve with a small radial contribution laterally. Action: primary elbow flexor in all forearm positions.'},
  {aliases:['brachioradialis'],text:'Origin: proximal lateral supracondylar ridge of humerus. Insertion: lateral distal radius near the styloid process. Innervation: radial nerve. Action: flexes the elbow most effectively in the mid-prone position.'},
  {aliases:['pronator teres'],text:'Origin: medial epicondyle of humerus and coronoid process of ulna. Insertion: lateral surface of mid-radius. Innervation: median nerve. Action: pronates the forearm and assists elbow flexion.'},
  {aliases:['flexor carpi radialis'],text:'Origin: common flexor origin at the medial epicondyle. Insertion: bases of the second and third metacarpals. Innervation: median nerve. Action: flexes and abducts the wrist.'},
  {aliases:['palmaris longus'],text:'Origin: medial epicondyle through the common flexor tendon. Insertion: flexor retinaculum and palmar aponeurosis. Innervation: median nerve. Action: weak wrist flexion and tensioning of the palmar aponeurosis.'},
  {aliases:['flexor carpi ulnaris'],text:'Origin: medial epicondyle, olecranon and posterior ulna. Insertion: pisiform with extensions to hamate and base of fifth metacarpal. Innervation: ulnar nerve. Action: flexes and adducts the wrist.'},
  {aliases:['flexor digitorum superficialis'],text:'Origin: humeroulnar head from medial epicondyle/coronoid and radial head from proximal radius. Insertion: sides of middle phalanges of digits 2–5. Innervation: median nerve. Action: flexes proximal interphalangeal joints and assists flexion at MCP joints and wrist.'},
  {aliases:['flexor digitorum profundus'],text:'Origin: proximal ulna and interosseous membrane. Insertion: bases of distal phalanges of digits 2–5. Innervation: lateral half by anterior interosseous branch of median nerve; medial half by ulnar nerve. Action: flexes distal interphalangeal joints.'},
  {aliases:['flexor pollicis longus'],text:'Origin: anterior radius and adjacent interosseous membrane. Insertion: base of distal phalanx of thumb. Innervation: anterior interosseous nerve from median nerve. Action: flexes the thumb, especially at the interphalangeal joint.'},
  {aliases:['pronator quadratus'],text:'Origin: distal anterior ulna. Insertion: distal anterior radius. Innervation: anterior interosseous nerve. Action: pronates the forearm and binds radius and ulna together distally.'},
  {aliases:['supinator'],text:'Origin: lateral epicondyle, radial collateral/annular ligament complex and supinator crest of ulna. Insertion: proximal third of radius. Innervation: deep branch of radial nerve. Action: supinates the forearm.'},

  {aliases:['axillary artery'],text:'Begins: continuation of the subclavian artery at the lateral border of the first rib. Ends: becomes the brachial artery at the inferior border of teres major. Course: divided into three parts by pectoralis minor. Major branches include superior thoracic, thoracoacromial, lateral thoracic, subscapular and anterior/posterior circumflex humeral arteries.'},
  {aliases:['brachial artery'],text:'Begins: continuation of the axillary artery below the inferior border of teres major. Course: descends in the arm with the median nerve changing position around it. Ends: in the cubital fossa by dividing into radial and ulnar arteries. Major branches include profunda brachii and superior/inferior ulnar collateral arteries.'},
  {aliases:['profunda brachii artery','deep brachial artery'],text:'Origin: major proximal branch of the brachial artery. Course: accompanies the radial nerve through the triangular interval and along the posterior humerus. It contributes to the arterial network around the elbow and anastomoses proximally with posterior circumflex humeral branches.'},
  {aliases:['radial artery'],text:'Begins: terminal branch of the brachial artery in the cubital fossa. Course: descends along the lateral forearm, passes through the anatomical snuffbox and enters the hand. It contributes mainly to the deep palmar arch.'},
  {aliases:['ulnar artery'],text:'Begins: terminal branch of the brachial artery in the cubital fossa. Course: passes deep in the proximal anterior forearm and descends on the ulnar side with the ulnar nerve distally. It contributes mainly to the superficial palmar arch.'},
  {aliases:['cephalic vein'],text:'Location/course: superficial vein on the lateral/radial side of the upper limb. It ascends through the deltopectoral groove/triangle and terminates in the axillary vein.'},
  {aliases:['basilic vein'],text:'Location/course: superficial vein on the medial side of the upper limb. It ascends the arm, pierces deep fascia and joins the deep venous system; around the inferior border of teres major the venous pathway continues as the axillary vein.'},
  {aliases:['median cubital vein'],text:'Location: superficial vein across the cubital fossa, typically connecting cephalic and basilic veins. It is a common site for venipuncture because it is superficial and relatively fixed.'},
  {aliases:['suprascapular nerve'],text:'Origin: upper trunk of the brachial plexus, mainly C5–C6. Course: passes toward the suprascapular notch, usually beneath the superior transverse scapular ligament, then supplies supraspinatus and continues around the scapular spine to infraspinatus. It also carries articular fibers to the shoulder region.'},
  {aliases:['axillary nerve'],text:'Origin: posterior cord of brachial plexus, mainly C5–C6. Course: travels with the posterior circumflex humeral vessels through the quadrangular space and around the surgical neck of humerus. Motor: deltoid and teres minor. Sensory: skin over the superolateral arm.'},
  {aliases:['musculocutaneous nerve'],text:'Origin: lateral cord of brachial plexus, C5–C7. Course: usually pierces coracobrachialis, descends between biceps and brachialis, then continues as the lateral cutaneous nerve of the forearm. Motor: anterior arm flexors.'},
  {aliases:['median nerve'],text:'Origin: union of lateral and medial roots from the brachial plexus. Course: descends with the brachial artery, passes through the cubital fossa, between the heads of pronator teres and into the anterior forearm, then through the carpal tunnel. Motor: most forearm flexor-pronators and thenar/lateral lumbrical muscles. Sensory: lateral palm and lateral three-and-a-half digits.'},
  {aliases:['ulnar nerve'],text:'Origin: medial cord of brachial plexus, mainly C8–T1. Course: passes posterior to the medial epicondyle, enters the forearm between heads of flexor carpi ulnaris and descends toward Guyon region at the wrist. Motor: flexor carpi ulnaris, medial FDP and most intrinsic hand muscles. Sensory: medial one-and-a-half digits and adjacent hand.'},
  {aliases:['radial nerve'],text:'Origin: posterior cord of brachial plexus, C5–T1. Course: accompanies profunda brachii through the triangular interval and radial groove, then comes anterior near the lateral elbow and divides into superficial and deep branches. Motor: posterior arm and forearm extensors. Sensory: posterior arm/forearm and dorsolateral hand.'},
  {aliases:['long thoracic nerve'],text:'Origin: anterior rami C5–C7. Course: descends on the superficial surface of serratus anterior along the lateral thoracic wall. Motor: serratus anterior. Injury may impair scapular protraction/upward rotation and produce winging.'},
  {aliases:['dorsal scapular nerve'],text:'Origin: usually C5 root. Course: passes posteriorly toward the medial scapular border, commonly deep to levator scapulae and with the dorsal scapular vascular territory. Motor: rhomboids and usually levator scapulae.'},

  {aliases:['hip bone','os coxae','coxal bone'],text:'Location: each half of the pelvic girdle, formed by fused ilium, ischium and pubis. The acetabulum receives the femoral head; the obturator foramen is mostly closed by obturator membrane. Major attachment landmarks include the iliac crest and gluteal lines, ischial spine/tuberosity and pubic rami.'},
  {aliases:['femur'],text:'Location: thigh bone between hip and knee. Articulations: head with acetabulum; distal condyles with tibia and patella. Major attachments include the greater and lesser trochanters, gluteal tuberosity, linea aspera and epicondylar regions.'},
  {aliases:['patella'],text:'Location: sesamoid bone embedded in the quadriceps tendon anterior to the knee. Its posterior articular surface contacts the femoral trochlea. The quadriceps tendon attaches superiorly and the patellar ligament continues from its apex to the tibial tuberosity.'},
  {aliases:['tibia'],text:'Location: medial weight-bearing bone of the leg. Proximally its condyles articulate with the femur; the tibial tuberosity receives the patellar ligament. Distally it contributes the medial malleolus and articulates with the talus.'},
  {aliases:['fibula'],text:'Location: slender lateral bone of the leg, primarily for muscle and ligament attachment rather than weight bearing. The head articulates with the tibia; distally it forms the lateral malleolus and helps stabilize the ankle mortise.'},
  {aliases:['hip joint'],text:'Location: synovial ball-and-socket joint between the femoral head and acetabulum. The acetabular labrum deepens the socket. The capsule and iliofemoral, pubofemoral and ischiofemoral ligaments provide strong stability while allowing flexion/extension, abduction/adduction and rotation.'},
  {aliases:['knee joint'],text:'Location: articulation of distal femoral condyles with proximal tibia, with the patella anteriorly. Stabilizers include menisci, ACL, PCL, tibial and fibular collateral ligaments, patellar ligament and posterior capsular reinforcements. It primarily allows flexion/extension with limited rotation.'},
  {aliases:['ankle joint','talocrural joint'],text:'Location: hinge joint where the distal tibia and fibula form a mortise around the talus. Medially it is supported by the deltoid ligament; laterally by anterior/posterior talofibular and calcaneofibular ligaments. Main motions are dorsiflexion and plantarflexion.'},
  {aliases:['anterior cruciate ligament','acl'],text:'Attachment/course: from the anterior intercondylar area of the tibia to the posteromedial surface of the lateral femoral condyle. Function: resists anterior translation of the tibia and contributes to rotational stability.'},
  {aliases:['posterior cruciate ligament','pcl'],text:'Attachment/course: from the posterior intercondylar area of the tibia to the anterolateral surface of the medial femoral condyle. Function: resists posterior translation of the tibia and stabilizes the flexed knee.'},
  {aliases:['patellar ligament'],text:'Attachment: continuation of the quadriceps mechanism from the apex and adjacent margins of the patella to the tibial tuberosity. It transmits quadriceps force for knee extension.'},
  {aliases:['tibial collateral ligament','medial collateral ligament'],text:'Attachment: medial femoral epicondylar region to the medial tibia, with deep fibers related to the medial meniscus. Function: resists valgus stress and contributes to medial knee stability.'},
  {aliases:['fibular collateral ligament','lateral collateral ligament'],text:'Attachment: lateral femoral epicondyle to the head of the fibula. It is separate from the lateral meniscus. Function: resists varus stress and contributes to lateral knee stability.'},
  {aliases:['deltoid ligament'],text:'Location: strong medial ligament complex of the ankle. Attachment: fans from the medial malleolus to the talus, calcaneus and navicular. Function: resists excessive eversion and stabilizes the medial ankle.'},
  {aliases:['anterior talofibular ligament'],text:'Attachment: lateral malleolus to the talus anteriorly. It is taut especially in plantarflexion and resists anterior translation/inversion of the talus; it is the lateral ankle ligament most commonly injured.'},
  {aliases:['calcaneofibular ligament'],text:'Attachment: lateral malleolus to lateral calcaneus. Function: supports the lateral ankle and resists inversion, especially with the ankle closer to neutral/dorsiflexion.'},

  {aliases:['gluteus maximus'],text:'Origin: posterior ilium behind the posterior gluteal line, dorsal sacrum/coccyx and associated ligaments. Insertion: iliotibial tract and gluteal tuberosity of femur. Innervation: inferior gluteal nerve. Blood supply: superior and inferior gluteal arteries. Action: powerful hip extension and lateral rotation.'},
  {aliases:['gluteus medius'],text:'Origin: external ilium between anterior and posterior gluteal lines. Insertion: lateral surface of greater trochanter. Innervation: superior gluteal nerve. Blood supply: superior gluteal artery. Action: abducts and medially rotates thigh and stabilizes the pelvis during gait.'},
  {aliases:['gluteus minimus'],text:'Origin: external ilium between anterior and inferior gluteal lines. Insertion: anterior surface of greater trochanter. Innervation: superior gluteal nerve. Blood supply: superior gluteal artery. Action: abducts/medially rotates the thigh and stabilizes the pelvis.'},
  {aliases:['tensor fasciae latae'],text:'Origin: anterior superior iliac spine and adjacent anterior iliac crest. Insertion: iliotibial tract, continuing to lateral tibia. Innervation: superior gluteal nerve. Action: flexes, abducts and medially rotates the thigh and tensions the iliotibial tract.'},
  {aliases:['piriformis'],text:'Origin: anterior surface of sacrum. Insertion: superior border of greater trochanter. Course: exits the pelvis through the greater sciatic foramen and divides that foramen into supra- and infrapiriform spaces. Innervation: nerve to piriformis. Action: lateral rotation of the extended thigh and abduction of the flexed thigh.'},
  {aliases:['obturator internus'],text:'Origin: pelvic surface of obturator membrane and surrounding bone. Insertion: medial surface of greater trochanter after the tendon turns through the lesser sciatic foramen. Innervation: nerve to obturator internus. Action: lateral rotation and stabilization of the hip.'},
  {aliases:['quadratus femoris'],text:'Origin: lateral border of ischial tuberosity. Insertion: quadrate tubercle/intertrochanteric crest region of femur. Innervation: nerve to quadratus femoris. Action: lateral rotation and adduction of the thigh.'},
  {aliases:['psoas major'],text:'Origin: T12–L5 vertebral bodies/discs and lumbar transverse processes. Insertion: lesser trochanter through the iliopsoas tendon. Innervation: anterior rami of lumbar spinal nerves. Action: strong hip flexion and trunk flexion when the femur is fixed.'},
  {aliases:['iliacus'],text:'Origin: iliac fossa and inner iliac region. Insertion: lesser trochanter with psoas major as iliopsoas. Innervation: femoral nerve. Action: hip flexion.'},
  {aliases:['iliopsoas'],text:'Components: psoas major and iliacus. Insertion: lesser trochanter of femur. Function: principal hip flexor and important postural muscle; its components arise from the lumbar spine and iliac fossa respectively.'},
  {aliases:['quadratus lumborum'],text:'Origin: iliac crest and iliolumbar ligament. Insertion: twelfth rib and transverse processes of upper lumbar vertebrae. Innervation: T12 and anterior rami of upper lumbar nerves. Action: lateral flexion of the trunk and fixation of the twelfth rib during respiration.'},
  {aliases:['femoral nerve'],text:'Origin: posterior divisions of L2–L4 lumbar plexus. Course: emerges lateral to psoas major, passes between psoas and iliacus and deep to the inguinal ligament into the femoral triangle. Motor: anterior thigh. Sensory: anterior thigh and medial leg/foot through saphenous nerve.'},
  {aliases:['obturator nerve'],text:'Origin: anterior divisions of L2–L4 lumbar plexus. Course: emerges medial to psoas, crosses the pelvic wall and passes through the obturator canal. Motor: mainly thigh adductors. Sensory: medial thigh and articular branches.'},
  {aliases:['sciatic nerve'],text:'Origin: lumbosacral plexus, L4–S3. Course: usually exits the greater sciatic foramen inferior to piriformis, descends deep to gluteus maximus and along the posterior thigh, then divides into tibial and common fibular components. Motor: hamstrings and all muscles below the knee through its branches.'},
  {aliases:['superior gluteal nerve'],text:'Origin: sacral plexus, L4–S1. Course: exits the greater sciatic foramen superior to piriformis with superior gluteal vessels. Motor: gluteus medius, gluteus minimus and tensor fasciae latae.'},
  {aliases:['inferior gluteal nerve'],text:'Origin: sacral plexus, L5–S2. Course: exits the greater sciatic foramen inferior to piriformis. Motor: gluteus maximus.'},
  {aliases:['femoral artery'],text:'Begins: continuation of the external iliac artery distal to the inguinal ligament. Course: passes through the femoral triangle and adductor canal. Ends: becomes the popliteal artery after passing through the adductor hiatus.'},
  {aliases:['popliteal artery'],text:'Begins: continuation of the femoral artery after the adductor hiatus. Course: runs deep through the popliteal fossa behind the knee. Ends: divides into anterior and posterior tibial arteries near the lower border of popliteus.'},
  {aliases:['great saphenous vein'],text:'Begins: medial side of the dorsal venous network of the foot. Course: passes anterior to the medial malleolus and ascends along the medial leg and thigh. Ends: joins the femoral vein at the saphenous opening.'},

  {aliases:['atlas','c1 vertebra','c1'],text:'Location: first cervical vertebra, supporting the skull. It has anterior and posterior arches and large lateral masses but no typical vertebral body or spinous process. Superior articular facets receive the occipital condyles at the atlanto-occipital joints. The dens of C2 is held against the anterior arch by the transverse ligament of the atlas.'},
  {aliases:['axis','c2 vertebra','c2'],text:'Location: second cervical vertebra. Its dens projects superiorly into the ring of the atlas and acts as the pivot for rotation at the atlanto-axial joint. The transverse ligament of the atlas holds the dens against the anterior arch of C1.'},
  {aliases:['atlanto-occipital joint'],text:'Location: between occipital condyles and superior articular facets of C1. Reinforced by anterior and posterior atlanto-occipital membranes. Main movement: flexion/extension of the head, with small lateral flexion.'},
  {aliases:['atlanto-axial joint'],text:'Location: joint complex between C1 and C2. The median joint is between dens and anterior arch/transverse ligament; paired lateral joints lie between articular facets. Main movement: rotation of the head and atlas around the dens.'},
  {aliases:['anterior longitudinal ligament'],text:'Attachment/course: broad ligament along the anterior surfaces of vertebral bodies and intervertebral discs from the upper spine toward the sacrum. Function: strongly limits excessive spinal extension.'},
  {aliases:['posterior longitudinal ligament'],text:'Attachment/course: runs along the posterior surfaces of vertebral bodies inside the vertebral canal. Function: limits spinal flexion and helps restrain posterior disc protrusion, although it is narrower than the anterior longitudinal ligament.'},
  {aliases:['nuchal ligament'],text:'Attachment/course: midline elastic/fibrous sheet in the posterior neck extending from the occipital region to the spinous process of C7, with attachment to cervical spinous processes. Function: supports the head and provides attachment for several posterior neck and back muscles.'},
  {aliases:['transverse ligament of atlas'],text:'Attachment: spans between the medial sides of the lateral masses of C1 behind the dens. Function: holds the dens against the anterior arch and prevents posterior displacement of the dens toward the spinal cord.'},
  {aliases:['spinal cord'],text:'Location: within the vertebral canal, continuous superiorly with the medulla at the foramen magnum. In adults it typically ends as the conus medullaris around the upper lumbar level, with cauda equina roots continuing inferiorly. It is enclosed by dura, arachnoid and pia mater.'},
  {aliases:['dorsal root ganglion','spinal ganglion'],text:'Location: enlargement on the dorsal root, typically near the intervertebral foramen. It contains cell bodies of pseudounipolar sensory neurons whose peripheral processes receive sensation and central processes enter the spinal cord.'},

  {aliases:['diaphragm'],text:'Location: musculotendinous partition between thoracic and abdominal cavities. Origin/attachments: xiphoid region, lower ribs/costal cartilages and lumbar vertebral region through crura and arcuate ligaments. Insertion: central tendon. Innervation: phrenic nerve, C3–C5. Major openings: caval opening T8, esophageal hiatus T10, aortic hiatus T12.'},
  {aliases:['rectus abdominis'],text:'Origin: pubic crest and pubic symphysis. Insertion: xiphoid process and costal cartilages of ribs 5–7. Innervation: thoracoabdominal nerves. Action: flexes the trunk, compresses abdominal contents and stabilizes the pelvis.'},
  {aliases:['external oblique'],text:'Origin: external surfaces of lower eight ribs. Insertion: linea alba, pubic tubercle and anterior iliac crest through a broad aponeurosis. Innervation: thoracoabdominal nerves and subcostal nerve. Fibers run inferomedially.'},
  {aliases:['internal oblique'],text:'Origin: thoracolumbar fascia, iliac crest and lateral inguinal ligament. Insertion: lower ribs, linea alba and pubic region through conjoint tendon. Innervation: thoracoabdominal nerves and L1 branches. Fibers generally run superomedially.'},
  {aliases:['transversus abdominis'],text:'Origin: internal lower costal cartilages, thoracolumbar fascia, iliac crest and lateral inguinal ligament. Insertion: linea alba and pubic region via aponeurosis/conjoint tendon. Innervation: thoracoabdominal nerves and L1 branches. Action: compresses abdominal contents and stabilizes the trunk.'},
  {aliases:['inguinal ligament'],text:'Attachment: thickened inferior border of the external oblique aponeurosis extending from ASIS to pubic tubercle. It forms the floor of the inguinal canal and marks the transition where the external iliac vessels become femoral vessels.'},
  {aliases:['esophagus'],text:'Course: muscular tube from pharynx through the thorax to the stomach, passing the diaphragm through the esophageal hiatus at about T10. The vagal trunks accompany it through the hiatus. Abdominal blood supply includes esophageal branches of the left gastric and inferior phrenic arteries.'},
  {aliases:['trachea'],text:'Location/course: airway from the larynx into the thorax, supported by cartilaginous rings and posterior membranous wall. Blood supply in the neck includes inferior and superior thyroid arterial branches; thoracic portions receive additional branches. Sensory/autonomic innervation includes vagal/recurrent laryngeal and sympathetic fibers.'},

  {aliases:['common carotid artery'],text:'Course: ascends in the carotid sheath region and divides into internal and external carotid arteries near the upper border of the thyroid cartilage. The right common carotid begins from the brachiocephalic trunk; the left begins directly from the aortic arch.'},
  {aliases:['internal carotid artery'],text:'Begins: carotid bifurcation. Course: ascends in the neck without giving cervical branches, enters the skull through the carotid canal and supplies the brain and orbit through intracranial branches.'},
  {aliases:['external carotid artery'],text:'Begins: carotid bifurcation. Course: ascends in the neck and gives multiple branches to the face, scalp, tongue, pharynx and neck before terminating mainly as maxillary and superficial temporal arteries.'},
  {aliases:['internal jugular vein'],text:'Begins: continuation of the intracranial venous drainage at the jugular foramen. Course: descends within the carotid sheath and joins the subclavian vein behind the sternoclavicular region to form the brachiocephalic vein.'},
  {aliases:['vertebral artery'],text:'Origin: subclavian artery. Course: ascends through transverse foramina of the cervical vertebrae, usually C6 to C1, curves around the atlas and enters the cranial cavity through the foramen magnum. It contributes to the vertebrobasilar circulation.'},
  {aliases:['phrenic nerve'],text:'Origin: anterior rami C3–C5. Course: descends on the anterior scalene, enters the thorax and runs to the diaphragm. Motor: diaphragm. Sensory: central diaphragm, fibrous pericardium and adjacent serous membranes.'},
  {aliases:['vagus nerve'],text:'Cranial nerve X. Course: exits the skull through the jugular foramen, descends within the carotid sheath and enters the thorax. It contributes parasympathetic fibers to thoracic and abdominal viscera; in the esophageal plexus its fibers reorganize into anterior and posterior vagal trunks.'},
  {aliases:['recurrent laryngeal nerve'],text:'Branch of the vagus nerve. Course: loops around the right subclavian artery on the right and the aortic arch on the left, then ascends in the tracheoesophageal groove toward the larynx. It supplies most intrinsic laryngeal muscles and carries sensation below the vocal folds.'},

  {aliases:['heart'],text:'Location: middle mediastinum within the pericardial sac, with its apex directed inferolaterally to the left. Layers: epicardium, myocardium and endocardium. Autonomic innervation reaches it through superficial and deep cardiac plexuses; parasympathetic vagal fibers reduce rate while sympathetic fibers increase rate and force.'},
  {aliases:['pericardium'],text:'Location: sac surrounding the heart. Fibrous pericardium attaches inferiorly to the central tendon of the diaphragm and anteriorly through sternopericardial connections. Serous pericardium has parietal and visceral layers with a fluid-filled cavity between them. Sensory innervation of fibrous/parietal pericardium is mainly via the phrenic nerve.'},
  {aliases:['aortic arch'],text:'Course: continuation of the ascending aorta curving posteriorly and to the left before becoming descending thoracic aorta. Major branches are brachiocephalic trunk, left common carotid artery and left subclavian artery.'},
  {aliases:['brachiocephalic trunk'],text:'Origin: first major branch of the aortic arch. Course: ascends to the right and divides into the right common carotid and right subclavian arteries near the right sternoclavicular region.'},
  {aliases:['superior vena cava'],text:'Formation: union of the right and left brachiocephalic veins. Course: descends on the right side of the superior mediastinum and enters the right atrium. It receives systemic venous return from structures above the diaphragm, except most of the heart itself.'},
  {aliases:['inferior vena cava'],text:'Formation: union of the common iliac veins in the lower abdomen. Course: ascends on the right side of the vertebral column, passes through the diaphragm at the caval opening and enters the right atrium.'},
  {aliases:['azygos vein'],text:'Course: ascends along the right posterior thoracic wall, receiving posterior intercostal and related veins, then arches over the right lung root to enter the superior vena cava. It provides an important collateral pathway between superior and inferior venous systems.'},

  {aliases:['temporomandibular joint','tmj'],text:'Location: articulation between the mandibular condyle and mandibular fossa/articular tubercle of the temporal bone. An articular disc divides the joint cavity into compartments, allowing hinge and gliding movements for opening, closing and translation of the jaw.'},
  {aliases:['mandible'],text:'Location: lower jaw. Articulation: mandibular condyle with temporal bone at the TMJ. Attachments: temporalis inserts on the coronoid process; mylohyoid attaches along the mylohyoid line. The mental foramen transmits the mental nerve and vessels; the mandibular foramen leads into the mandibular canal.'},
  {aliases:['temporalis'],text:'Origin: temporal fossa and temporal fascia. Insertion: coronoid process and anterior ramus of mandible. Innervation: deep temporal branches of mandibular nerve, CN V3. Action: elevates the mandible; posterior fibers retract it.'},
  {aliases:['mylohyoid'],text:'Origin: mylohyoid line of mandible. Insertion: median raphe and hyoid bone. Innervation: nerve to mylohyoid from inferior alveolar nerve, CN V3. Action: elevates the floor of mouth and hyoid during swallowing.'},
  {aliases:['malleus'],text:'Location: middle ear ossicle attached to the tympanic membrane. The tensor tympani tendon attaches to the malleus and pulls it medially to damp tympanic membrane movement.'},
  {aliases:['stapes'],text:'Location: smallest auditory ossicle in the middle ear. Its footplate occupies the oval window leading to the vestibule of the inner ear. The stapedius muscle attaches to the stapes and is supplied by the facial nerve.'},
  {aliases:['optic chiasm'],text:'Location: ventral diencephalic region above the pituitary area. It is the site where nasal retinal fibers from each optic nerve cross to the opposite optic tract, allowing binocular visual fields to be represented in both hemispheres.'},
  {aliases:['falx cerebri'],text:'Location: vertical dural fold in the longitudinal fissure between the cerebral hemispheres. It attaches anteriorly near the crista galli and posteriorly blends with the tentorium cerebelli; dural venous sinuses run along its margins.'},
  {aliases:['tentorium cerebelli'],text:'Location: horizontal dural fold separating occipital lobes from the cerebellum. It attaches to the petrous temporal region and occipital bone and forms the tentorial notch around the brainstem.'},

  {aliases:['sternocleidomastoid','scm'],text:'Origin: manubrium and medial clavicle. Insertion: mastoid process and adjacent superior nuchal line. Innervation: spinal accessory nerve (CN XI) with cervical sensory/proprioceptive fibers. Action: unilateral contraction rotates the head to the opposite side and laterally flexes it; bilateral contraction flexes the neck and can assist inspiration.'},
  {aliases:['platysma'],text:'Origin: superficial fascia over the upper thorax and shoulder region. Insertion: lower border of mandible and skin/muscles of the lower face. Innervation: cervical branch of facial nerve (CN VII). Action: tenses neck skin and depresses the lower lip/mandible.'},
  {aliases:['anterior scalene'],text:'Origin: anterior tubercles of transverse processes C3–C6. Insertion: first rib. Innervation: anterior rami of cervical nerves. Action: elevates the first rib and flexes/laterally flexes the neck. The subclavian vein lies anterior to it, while the subclavian artery and brachial plexus pass posteriorly between anterior and middle scalenes.'},
  {aliases:['middle scalene'],text:'Origin: posterior tubercles of cervical transverse processes. Insertion: superior surface of the first rib posterior to the subclavian groove. Innervation: cervical anterior rami. Action: elevates the first rib and laterally flexes the neck. The brachial plexus and subclavian artery pass between this muscle and anterior scalene.'},
  {aliases:['posterior scalene'],text:'Origin: posterior tubercles of lower cervical transverse processes. Insertion: external surface of the second rib. Innervation: cervical anterior rami. Action: elevates the second rib and assists lateral flexion of the neck.'},
  {aliases:['longus capitis'],text:'Origin: anterior tubercles of transverse processes C3–C6. Insertion: basilar part of occipital bone. Innervation: anterior rami of upper cervical nerves. Action: flexes and stabilizes the head and upper cervical spine.'},
  {aliases:['longus colli'],text:'Location: deep prevertebral muscle along the anterior cervical and upper thoracic spine. Attachments: spans upper thoracic/lower cervical vertebral bodies and cervical transverse processes through superior oblique, vertical and inferior oblique portions. Innervation: cervical anterior rami. Action: cervical flexion with slight rotation/stabilization.'},
  {aliases:['lateral pterygoid'],text:'Origin: superior head from infratemporal surface of greater wing of sphenoid; inferior head from lateral surface of lateral pterygoid plate. Insertion: anterior neck of mandibular condyle and TMJ disc/capsule region. Innervation: nerve to lateral pterygoid from CN V3. Action: protrudes and helps depress the mandible; unilateral action contributes to side-to-side movement.'},
  {aliases:['medial pterygoid'],text:'Origin: mainly medial surface of lateral pterygoid plate/pterygoid fossa with a superficial maxillary/palatal contribution. Insertion: medial surface of mandibular ramus and angle. Innervation: nerve to medial pterygoid from CN V3. Action: elevates and protrudes the mandible and assists grinding movements.'},

  {aliases:['adductor longus'],text:'Origin: body of pubis near the pubic symphysis. Insertion: middle third of linea aspera of femur. Innervation: obturator nerve. Action: adducts the thigh and assists flexion.'},
  {aliases:['adductor brevis'],text:'Origin: body and inferior ramus of pubis. Insertion: pectineal line and proximal linea aspera. Innervation: obturator nerve. Action: adducts and weakly flexes the thigh.'},
  {aliases:['adductor magnus'],text:'Origin: inferior pubic/ischial rami and ischial tuberosity. Insertion: linea aspera/medial supracondylar line and adductor tubercle. Innervation: obturator nerve to adductor part and tibial division of sciatic nerve to hamstring part. Action: strong adduction; portions flex or extend the hip.'},
  {aliases:['gracilis'],text:'Origin: body and inferior ramus of pubis. Insertion: medial proximal tibia as part of the pes anserinus. Innervation: obturator nerve. Action: adducts the thigh, flexes the knee and medially rotates the leg.'},
  {aliases:['obturator externus'],text:'Origin: external surface of obturator membrane and adjacent pubis/ischium. Insertion: trochanteric fossa of femur. Innervation: obturator nerve. Action: laterally rotates the thigh and stabilizes the femoral head.'},
  {aliases:['tibialis anterior'],text:'Origin: lateral condyle and upper lateral tibia with adjacent interosseous membrane. Insertion: medial cuneiform and base of first metatarsal. Innervation: deep fibular nerve, mainly L4–L5. Action: dorsiflexes and inverts the foot.'},
  {aliases:['fibularis tertius','peroneus tertius'],text:'Origin: distal anterior fibula and interosseous membrane. Insertion: dorsal base of fifth metatarsal. Innervation: deep fibular nerve. Action: dorsiflexes and everts the foot.'},
  {aliases:['extensor hallucis longus'],text:'Origin: middle anterior fibula and interosseous membrane. Insertion: dorsal base of distal phalanx of great toe. Innervation: deep fibular nerve. Action: extends the great toe and dorsiflexes the ankle.'},
  {aliases:['extensor digitorum longus'],text:'Origin: lateral tibial condyle, anterior fibula and interosseous membrane. Insertion: extensor expansions of lateral four toes. Innervation: deep fibular nerve. Action: extends toes 2–5 and dorsiflexes the ankle; assists eversion.'},
  {aliases:['fibularis longus','peroneus longus'],text:'Origin: head and upper lateral fibula. Insertion: plantar base of first metatarsal and medial cuneiform after crossing the sole. Innervation: superficial fibular nerve. Action: everts and plantarflexes the foot and supports the transverse/longitudinal arches.'},
  {aliases:['fibularis brevis','peroneus brevis'],text:'Origin: distal lateral fibula. Insertion: tuberosity at base of fifth metatarsal. Innervation: superficial fibular nerve. Action: everts and weakly plantarflexes the foot.'},
  {aliases:['deep fibular nerve','deep peroneal nerve'],text:'Origin: terminal branch of the common fibular nerve near the fibular neck. Course: enters the anterior leg, descends with the anterior tibial vessels along the interosseous membrane and continues onto the dorsum of the foot. Motor: anterior leg and short toe extensors. Sensory: first interdigital cleft.'},
  {aliases:['superficial fibular nerve','superficial peroneal nerve'],text:'Origin: terminal branch of the common fibular nerve near the fibular neck. Course: descends in the lateral compartment between fibularis muscles, then pierces deep fascia in the distal leg. Motor: fibularis longus and brevis. Sensory: most of the dorsum of foot and distal anterolateral leg.'},
  {aliases:['sacrospinous ligament'],text:'Attachment: sacrum/coccyx to ischial spine. Together with the sacrotuberous ligament it converts the sciatic notches into greater and lesser sciatic foramina and stabilizes the sacroiliac region.'},
  {aliases:['sacrotuberous ligament'],text:'Attachment: posterior sacrum/ilium to ischial tuberosity. It works with the sacrospinous ligament to define the greater and lesser sciatic foramina and resists excessive sacral nutation.'},
  {aliases:['obturator membrane'],text:'Attachment: fibrous sheet closing most of the obturator foramen between pubis and ischium. It provides origin for obturator internus and externus and leaves a superior obturator canal for the obturator nerve and vessels.'},
  {aliases:['sacroiliac joint','si joint'],text:'Location: articulation between auricular surfaces of sacrum and ilium. It transfers load from the axial skeleton to the pelvic girdle and is reinforced by strong anterior, interosseous and posterior sacroiliac ligaments.'},
  {aliases:['pubic symphysis'],text:'Location: midline secondary cartilaginous joint between the right and left pubic bodies. The symphyseal surfaces are united by a fibrocartilaginous disc and strengthened by surrounding pubic ligaments.'},
  {aliases:['pudendal nerve'],text:'Origin: ventral rami S2–S4. Course: exits the pelvis through the greater sciatic foramen, hooks around the ischial spine/sacrospinous ligament, enters the lesser sciatic foramen and travels in the pudendal canal. Motor/sensory: principal somatic nerve of the perineum, including external sphincters and external genital skin.'},

  {aliases:['subclavian artery'],text:'Origin: right from brachiocephalic trunk, left directly from the aortic arch. Course: passes over the first rib and is divided into three parts by anterior scalene. Ends: becomes the axillary artery at the lateral border of the first rib. Major branches include vertebral, internal thoracic and thyrocervical/costocervical branches.'},
  {aliases:['external jugular vein'],text:'Course: superficial vein descending across the sternocleidomastoid region. It drains superficial scalp/face and neck territories and terminates in the subclavian vein.'},
  {aliases:['facial artery'],text:'Origin: external carotid artery. Course: runs deep in the upper neck, hooks around the inferior border of the mandible anterior to masseter and then follows a tortuous superficial course across the face toward the medial canthus. Branches include inferior/superior labial and lateral nasal branches.'},
  {aliases:['superficial temporal artery'],text:'Origin: terminal branch of the external carotid artery near the parotid region. Course: ascends anterior to the ear into the scalp; its pulse can be palpated superficially. It gives a transverse facial branch that crosses the cheek near the parotid duct.'},
  {aliases:['facial vein'],text:'Begins: near the medial canthus as continuation of the angular vein formed by supraorbital and supratrochlear venous channels. Course: descends across the face, receives nasal and labial tributaries and communicates with deeper venous pathways before draining toward the internal jugular system through the common facial vein.'},
  {aliases:['ophthalmic artery'],text:'Origin: internal carotid artery. Course: enters the orbit through the optic canal with the optic nerve and supplies the orbit, eye and related forehead/nasal territories through multiple branches.'},
  {aliases:['ophthalmic vein','superior ophthalmic vein'],text:'Course: drains orbital structures and communicates anteriorly with facial/angular veins. It passes through the superior orbital fissure and drains into the cavernous sinus, forming an important valveless connection between superficial facial and intracranial venous systems.'},
  {aliases:['optic nerve','cranial nerve ii','cn ii'],text:'Course: carries retinal visual information from the globe through the optic canal into the cranial cavity, where the two optic nerves meet at the optic chiasm. It travels through the optic canal with the ophthalmic artery.'},

  {aliases:['kidney'],text:'Location: retroperitoneal organ on the posterior abdominal wall. At the renal hilum, the renal vein is generally anterior to the renal artery, with the renal pelvis/ureter more posterior. Internally, cortex surrounds medulla; renal pyramids drain at papillae into minor then major calyces, renal pelvis and ureter.'},
  {aliases:['renal artery'],text:'Origin: abdominal aorta. Course: passes toward the renal hilum and divides into segmental branches, then interlobar, arcuate and interlobular/cortical radiate arteries within the kidney. Accessory renal arteries are a common anatomical variation.'},
  {aliases:['renal vein'],text:'Course: drains blood from the kidney and lies anterior to the renal artery at the hilum. The right and left renal veins empty into the inferior vena cava; the left is longer because the IVC lies to the right of midline.'},
  {aliases:['ureter'],text:'Begins: renal pelvis. Course: retroperitoneal muscular tube descending on the posterior abdominal wall, crossing into the pelvis and entering the urinary bladder obliquely. It carries urine by peristalsis and has clinically important narrowings at the pelviureteric junction, pelvic brim and bladder wall.'},
  {aliases:['urinary bladder'],text:'Location: pelvic muscular reservoir posterior to the pubic symphysis. The ureters enter posterolaterally and the urethra exits inferiorly at the bladder neck. Its smooth muscle wall forms the detrusor.'},

  {aliases:['lung'],text:'Location: paired organs within pleural cavities. Each lung is connected to mediastinal structures at the root/hilum, where bronchi, pulmonary vessels, bronchial vessels, lymphatics and nerves pass. Bronchopulmonary segments are supplied by segmental bronchi and pulmonary arterial branches.'},
  {aliases:['pulmonary artery'],text:'Begins: pulmonary trunk from the right ventricle divides into right and left pulmonary arteries. Course: enters each lung root and branches alongside the bronchial tree. Function: carries deoxygenated blood to pulmonary capillary networks.'},
  {aliases:['pulmonary vein'],text:'Begins: pulmonary venous channels collecting oxygenated blood from lung capillaries. Course: usually two veins leave each lung and run independently of the bronchial branching pattern. Ends: left atrium.'},
  {aliases:['bronchial artery'],text:'Origin: mainly thoracic aorta or related branches. Course: follows the bronchi on their surfaces to supply the bronchial walls, connective tissue and visceral pleura as part of the systemic circulation.'},
  {aliases:['bronchial vein'],text:'Course: drains part of the bronchial systemic circulation. Right bronchial veins commonly drain to the azygos system; left bronchial veins drain toward accessory hemiazygos/superior intercostal venous pathways.'},
  {aliases:['pleura','parietal pleura','visceral pleura'],text:'Location: serous membrane around the lungs. Visceral pleura covers the lung surface; parietal pleura lines the thoracic wall, diaphragm and mediastinum. At the lung root the layers are continuous and form a pleural sleeve whose inferior extension contributes to the pulmonary ligament.'},
  {aliases:['pulmonary ligament'],text:'Attachment/location: inferior double-layered pleural fold extending below the lung root toward the mediastinum/esophageal region. It permits movement of root structures during respiration and helps anchor the lung inferiorly.'},
  {aliases:['intercostal nerve'],text:'Course: anterior ramus of a thoracic spinal nerve running in the neurovascular plane between internal and innermost intercostal muscles. Within the costal groove the main bundle is arranged superior-to-inferior as vein, artery, nerve (V-A-N).'},
  {aliases:['intercostal artery'],text:'Course: runs in the costal groove with the intercostal vein and nerve between internal and innermost intercostal muscles. Posterior intercostal arteries arise from thoracic aorta for most spaces, while upper spaces receive supply through the superior intercostal artery.'},
  {aliases:['intercostal vein'],text:'Course: runs in the costal groove above the intercostal artery and nerve in the main V-A-N bundle. Posterior intercostal veins drain primarily into the azygos/hemiazygos systems.'},
  {aliases:['external intercostal'],text:'Attachment: spans adjacent ribs, with fibers running inferoanteriorly. Function: elevates ribs during inspiration. Anteriorly the muscle is replaced by external intercostal membrane near the costal cartilage region.'},
  {aliases:['internal intercostal'],text:'Attachment: spans adjacent ribs deep to external intercostals, with fibers generally running inferoposteriorly. The main intercostal neurovascular bundle lies between the internal and innermost layers. Interosseous fibers mainly assist forced expiration.'},

  {aliases:['ovary'],text:'Location: paired gonad in the lateral pelvis, posterior to the broad-ligament region. Attachments: suspensory ligament carries ovarian vessels to the lateral ovary; ovarian ligament connects the ovary to the uterus. Blood supply: ovarian artery from abdominal aorta with anastomosis to uterine branches.'},
  {aliases:['ovarian artery'],text:'Origin: abdominal aorta below the renal arteries. Course: descends into the pelvis, crosses the iliac vessels and travels within the suspensory ligament of the ovary. It supplies ovary and uterine tube and anastomoses with uterine arterial branches.'},
  {aliases:['uterus'],text:'Location: pelvic organ between bladder and rectum, normally tilted forward. Support includes pelvic floor structures and ligamentous/fascial condensations; the round ligament passes toward the inguinal canal, while the broad ligament is a peritoneal fold related to uterus, tube and ovary.'},
  {aliases:['round ligament of uterus'],text:'Course/attachment: extends from the uterine horn region, passes through the inguinal canal and reaches the labia majora. It helps maintain the normal anteverted orientation of the uterus.'},
  {aliases:['testis','testes'],text:'Location: gonad within the scrotum. Coverings include tunica vaginalis and fibrous tunica albuginea. Seminiferous tubules produce sperm. The testicular artery descends from the abdominal aorta; venous return begins in the pampiniform plexus.'},
  {aliases:['ductus deferens','vas deferens'],text:'Course: thick-walled muscular duct carrying sperm from the epididymis within the spermatic cord, through the inguinal canal and into the pelvis, where it approaches the seminal vesicle duct to form the ejaculatory duct.'},

  {aliases:['thyroid cartilage'],text:'Location: largest laryngeal cartilage forming the anterior and lateral laryngeal framework. Features include superior/inferior horns, superior thyroid notch and oblique line for muscle attachment. Its inferior horn articulates with the cricoid cartilage.'},
  {aliases:['cricoid cartilage'],text:'Location: complete ring-shaped laryngeal cartilage below the thyroid cartilage, narrow anteriorly and broad posteriorly. It articulates superiorly with arytenoid cartilages and laterally with the inferior horns of the thyroid cartilage.'},
  {aliases:['arytenoid cartilage'],text:'Location: paired pyramidal cartilage on the superior posterior cricoid lamina. The vocal process attaches to the vocal ligament; the muscular process provides attachment for intrinsic laryngeal muscles controlling vocal-fold position.'},
  {aliases:['vocal ligament'],text:'Attachment: extends from the inner thyroid cartilage anteriorly to the vocal process of the arytenoid cartilage posteriorly. It forms the fibrous core of the true vocal fold and changes tension/position during phonation.'},
  {aliases:['thoracic duct'],text:'Course: principal lymphatic channel draining most of the body below the diaphragm and the left upper quadrant. It ascends through the thorax and empties into the venous system near the left venous angle at the junction of internal jugular and subclavian veins.'}

];

const normalize = (value:string) => value
  .toLowerCase()
  .replace(/\b(left|right|bilateral)\b/g,' ')
  .replace(/[^a-z0-9]+/g,' ')
  .trim()
  .replace(/\s+/g,' ');

export function lectureExplanation(name:string){
  const target=normalize(name);
  if(!target)return undefined;
  let best:{score:number;text:string}|undefined;
  for(const entry of STRUCTURE_DESCRIPTIONS){
    for(const alias of entry.aliases){
      const key=normalize(alias);
      let score=0;
      if(target===key)score=10000+key.length;
      else if(target.includes(key))score=key.length;
      else if(key.includes(target)&&target.length>=7)score=Math.floor(target.length/2);
      if(score&&(!best||score>best.score))best={score,text:entry.text};
    }
  }
  return best?.text;
}

export function hasLectureExplanation(name:string){
  return !!lectureExplanation(name);
}
