import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {DEFAULT_VISIBLE,SYSTEMS,EXPLANATIONS,explanation,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
import {ANATOMY_REGIONS,regionById,type RegionId} from './mj-regions';
import {resolveDissection} from './mj-dissection';
import {structureProfile} from './mj-structure-info';
import {normalizeAtlasSystems} from './mj-system-classifier';
import {buildUpperLimbMotion,NEUTRAL_POSE,sideRegionIds,type MotionPose,type Side} from './mj-motion';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
export default function Home(){
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 const [region,setRegion]=useState<RegionId>('whole-body'),[dissectionStage,setDissectionStage]=useState(0),[studySide,setStudySide]=useState<'both'|Side>('both');
 const [motionSide,setMotionSide]=useState<Side>('right'),[motionPose,setMotionPose]=useState<MotionPose>(NEUTRAL_POSE);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch(`${import.meta.env.BASE_URL}models/atlas.json`,{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy catalogue could not be loaded.');return r.json();}).then(data=>setAtlas(normalizeAtlasSystems(data as Atlas))).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.focusParts?(state.focusParts.includes(p.id)&&state.visible.includes(p.system))||state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,cameraFocusParts:c.elements,cameraFocusNonce:(s.cameraFocusNonce??0)+1,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],cameraFocusParts:[id],cameraFocusNonce:(s.cameraFocusNonce??0)+1,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);setRegion('whole-body');setDissectionStage(0);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 const currentRegion=regionById(region);
 const profile=chosen&&selected?structureProfile(chosen.name,selected.system):null;
 const filterSide=(ids:string[],side:'both'|Side)=>{if(side==='both')return ids;return ids.filter(id=>{const p=parts.get(id);if(!p)return false;const x=(p.bounds[0][0]+p.bounds[1][0])/2;return side==='right'?x<-.04:x>.04;});};
 const dissect=(nextStage:number)=>{if(!atlas||region==='whole-body')return;const resolved=resolveDissection(atlas,region,nextStage),ids=filterSide(resolved.partIds,studySide);setDissectionStage(resolved.stage);setChosen(null);setDetails(false);setPanel(null);setState(s=>({...s,focusParts:ids,selected:[],isolate:false,explode:0,rotate:false}));};
 const focusSide=(side:'both'|Side)=>{if(!atlas)return;setStudySide(side);if(region==='whole-body'){if(side==='both'){setState(s=>({...s,focusParts:undefined,cameraFocusParts:undefined,selected:[],partTransforms:undefined}));return;}const ids=sideRegionIds(atlas,side);setState(s=>({...s,focusParts:ids,cameraFocusParts:ids,cameraFocusNonce:(s.cameraFocusNonce??0)+1,selected:[],isolate:false,explode:0}));return;}const resolved=resolveDissection(atlas,region,dissectionStage),ids=filterSide(resolved.partIds,side);setState(s=>({...s,focusParts:ids,cameraFocusParts:side==='both'?undefined:ids,cameraFocusNonce:side==='both'?(s.cameraFocusNonce??0):(s.cameraFocusNonce??0)+1,selected:[],isolate:false,explode:0}));};
 const changeRegion=(next:RegionId)=>{setRegion(next);setDissectionStage(0);setChosen(null);setDetails(false);setState(s=>({...s,partTransforms:undefined}));setMotionPose(NEUTRAL_POSE);if(!atlas||next==='whole-body'){setStudySide('both');setState(s=>({...s,focusParts:undefined,cameraFocusParts:undefined,selected:[],isolate:false,explode:0,rotate:false,visible:DEFAULT_VISIBLE,partTransforms:undefined}));return;}const resolved=resolveDissection(atlas,next,0),ids=filterSide(resolved.partIds,studySide);setState(s=>({...s,focusParts:ids,selected:[],isolate:false,explode:0,rotate:false,visible:DEFAULT_VISIBLE,partTransforms:undefined}));};
 const activateMotionSide=(side:Side)=>{if(!atlas)return;setMotionSide(side);setStudySide(side);const ids=sideRegionIds(atlas,side),built=buildUpperLimbMotion(atlas,side,motionPose);if(built.warnings.length)setError(built.warnings.join(' '));else setError('');setState(s=>({...s,focusParts:ids,cameraFocusParts:ids,cameraFocusNonce:(s.cameraFocusNonce??0)+1,partTransforms:built.transforms,visible:DEFAULT_VISIBLE,selected:[],isolate:false,explode:0,rotate:false}));};
 const setJoint=(key:keyof MotionPose,value:number)=>{if(!atlas)return;const pose={...motionPose,[key]:value};setMotionPose(pose);const built=buildUpperLimbMotion(atlas,motionSide,pose);if(built.warnings.length)setError(built.warnings.join(' '));else setError('');setState(s=>({...s,partTransforms:built.transforms,rotate:false}));};
 const neutralMotion=()=>{setMotionPose(NEUTRAL_POSE);setState(s=>({...s,partTransforms:undefined}));};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> INTERACTIVE ANATOMY</div><h1>MJ Anatomy<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{atlas?atlas.parts.length.toLocaleString():'2,234'} modeled pieces <span>·</span> BodyParts3D <span>·</span> MJ build</div></header>
  <nav className="top-actions" aria-label="Explorer panels"><Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label="Search anatomy"><Search size={18}/><span>Find a structure</span><kbd>/</kbd></Button><Button variant="ghost" className="icon-button" aria-label="About this atlas" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button></nav>
  <section className="mj-region-bar glass" aria-label="MJ Anatomy region and dissection">
   <div className="mj-region-title"><strong>Dissection｜分層解剖</strong><span>Peel anatomy layer by layer</span></div>
   <div className="mj-region-tabs">{ANATOMY_REGIONS.map(r=><Button variant="ghost" key={r.id} className={region===r.id?'active':''} aria-pressed={region===r.id} onClick={()=>changeRegion(r.id)}>{r.name}</Button>)}</div>
   {region!=='whole-body'&&<div className="mj-dissection-control"><div><span className="eyebrow">{currentRegion.subtitle}</span><strong>{currentRegion.stages[dissectionStage]?.label}</strong><small>{currentRegion.stages[dissectionStage]?.description}</small></div><div className="mj-dissection-side"><Button variant="ghost" className={studySide==='both'?'active':''} onClick={()=>focusSide('both')}>Both</Button><Button variant="ghost" className={studySide==='left'?'active':''} onClick={()=>focusSide('left')}>Left focus</Button><Button variant="ghost" className={studySide==='right'?'active':''} onClick={()=>focusSide('right')}>Right focus</Button></div><div className="mj-dissection-actions"><Button variant="ghost" disabled={dissectionStage===0} onClick={()=>dissect(dissectionStage-1)}>Layer back｜上一層</Button><Button variant="ghost" disabled={dissectionStage>=currentRegion.stages.length-1} onClick={()=>dissect(dissectionStage+1)}>Dissect deeper｜向深層</Button></div></div>}
  </section>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label="Anatomical layers">
   <div className="panel-heading"><span>Systems</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label="Close systems"><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>All</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>Skeleton</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>Organs</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={`Show only ${s.name.toLowerCase()}`} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{s.name}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={`Show ${s.name.toLowerCase()}`} /></div>)}</div>
   <div className="panel-foot"><span>{visibleCount.toLocaleString()} pieces visible</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>Hide all</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label="Find anatomy"><div className="panel-heading"><span>Find a structure</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label="Close search"><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>c.name} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder="Heart, femur, cranial nerve…" aria-label="Search named anatomical structures" showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>No structures match your search.</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{c.name}</span><span className="small-number">{c.elements.length} {c.elements.length===1?'piece':'pieces'}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?'Showing up to 80 matches. Refine your search to find smaller structures.':'Start with a major organ, or search every named structure.'}</p></section>}
  <nav className="view-controls glass" aria-label="Camera controls">{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={`${v} view`} aria-label={`${v} view`}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?'Pause rotation':'Rotate body'} title="Auto rotate" className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label="Reset view and layers" title="Reset" onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?.name??'SELECTED STRUCTURE'):state.explode>.95?'ANATOMICAL INVENTORY':state.explode>.05?'SEPARATED STRUCTURES':'ADULT HUMAN · MALE'}</span><span className="caption-line"/></div>
  <section className="mj-motion-lab glass" aria-label="Upper limb motion lab">
   <div className="mj-motion-head"><div><span className="eyebrow">MOTION LAB｜關節活動</span><strong>{motionSide==='right'?'Right':'Left'} upper limb</strong></div><Button variant="ghost" onClick={neutralMotion}>Neutral｜復位</Button></div>
   <div className="mj-motion-sides"><Button variant="ghost" className={motionSide==='left'?'active':''} onClick={()=>activateMotionSide('left')}>Focus left</Button><Button variant="ghost" className={motionSide==='right'?'active':''} onClick={()=>activateMotionSide('right')}>Focus right</Button></div>
   <label className="mj-joint-control"><span>Shoulder abduction｜肩外展 <b>{Math.round(motionPose.shoulderAbduction)}°</b></span><Slider min={0} max={170} step={1} value={[motionPose.shoulderAbduction]} onValueChange={v=>setJoint('shoulderAbduction',Array.isArray(v)?v[0]:v)}/></label>
   <label className="mj-joint-control"><span>Elbow flexion｜屈肘 <b>{Math.round(motionPose.elbowFlexion)}°</b></span><Slider min={0} max={145} step={1} value={[motionPose.elbowFlexion]} onValueChange={v=>setJoint('elbowFlexion',Array.isArray(v)?v[0]:v)}/></label>
   <label className="mj-joint-control"><span>Forearm rotation｜前臂旋轉 <b>{Math.round(motionPose.forearmRotation)}°</b></span><Slider min={-80} max={80} step={1} value={[motionPose.forearmRotation]} onValueChange={v=>setJoint('forearmRotation',Array.isArray(v)?v[0]:v)}/></label>
   <small className="mj-motion-note">Drag the sliders to move the joints. Camera stays where you put it.</small>
  </section>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label="Open system layers"><Layers3 size={20}/><span>Systems</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">Explode anatomy</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>Assembled</span><span>Every piece</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label="Assemble and reset"><RotateCcw size={18}/><span>Reset</span></Button></div>
  <footer className="studio-footer"><span>Drag to move <b>·</b> Right-drag to rotate <b>·</b> Scroll / pinch to zoom <b>·</b> Tap a structure to focus</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>Source & credits <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>Preparing the anatomy</strong><span>{progress}% · Loading {atlas?.parts.length.toLocaleString()??'2,234'} pieces</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>Reload viewer</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{profile?.category??system?.name??'ANATOMY'}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{profile?.english??chosen?.name}{profile?.chinese&&<span className="structure-title-zh">{profile.chinese}</span>}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}`}><SheetDescription className="structure-description">{profile?.summaryEn??(chosen&&selected?explanation(chosen.name,selected.system):'')}</SheetDescription>{profile?.summaryZh&&<p className="structure-description zh-copy">{profile.summaryZh}</p>}{profile?.facts&&profile.facts.length>0&&<div className="bilingual-facts">{profile.facts.map((fact,i)=><div className="bilingual-fact" key={`${fact.labelEn}-${i}`}><div className="fact-label">{fact.labelEn}<span>{fact.labelZh}</span></div><div className="fact-value">{fact.valueEn}{fact.valueZh&&<span>{fact.valueZh}</span>}</div></div>)}</div>}{profile&&<span className="context-note">Study source · {profile.source}</span>}{chosen&&!profile&&!EXPLANATIONS[chosen.name.toLowerCase()]&&<span className="context-note">System overview · structure identified from source anatomy</span>}<div className="structure-meta"><span>Atlas reference<strong>{chosen?.id}</strong></span><span>Selected pieces<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>Included structures</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{p.name}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>And {selectedParts.length-50} more modeled pieces.</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">View anatomical source <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className="primary-action" onClick={()=>setState(s=>({...s,cameraFocusParts:s.selected,cameraFocusNonce:(s.cameraFocusNonce??0)+1,rotate:false}))}><Focus size={18}/>Focus / 放大<ChevronRight size={16}/></Button><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}>{state.isolate?'Show surrounding anatomy':'Isolate structure'}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>Clear selection</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">SOURCE & SCOPE</div><SheetTitle className="structure-title">A body, revealed.</SheetTitle><SheetDescription>Explore the adult male reference anatomy from BodyParts3D.</SheetDescription><div className="about-copy"><p><strong>Male · BodyParts3D</strong><br/>2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.</p><p>This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.</p><p>Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.</p><h3>Source</h3><p>BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">Dataset license <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">Original geometry & metadata <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">Read the source publication <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
